CREATE TABLE `code_attribute` (
  `CODE_ATTRIBUTE_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `MARK` varchar(255) NOT NULL COMMENT '一组信息的唯一标识,默认是表名',
  `COLUMN_NAME` varchar(255) NOT NULL COMMENT '表字段名',
  `ATTRIBUTE_NAME` varchar(255) DEFAULT NULL COMMENT 'java 属性名',
  `DESCRIPTION` varchar(500) NOT NULL COMMENT '描述信息',
  `EQUAL_SUPPORT` enum('NO','YES') NOT NULL COMMENT '是否支持equal查询',
  `IN_SUPPORT` enum('NO','YES') NOT NULL COMMENT '是否支持IN查询',
  `COMPARE_SUPPORT` enum('NO','YES') NOT NULL COMMENT '是否支持比较查询',
  `INDISTINCT_SUPPORT` enum('NO','YES') NOT NULL COMMENT '是否支持模糊查询',
  `IS_PRIMARY` enum('NO','YES') NOT NULL COMMENT '是否是主键',
  `SORT_ORDER` int(20) NOT NULL COMMENT '顺序',
  `INPUT_TIME` datetime NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`CODE_ATTRIBUTE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8;

CREATE TABLE `page_attribute` (
  `PAGE_ATTRIBUTE_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `VIEW_MARK` varchar(255) DEFAULT NULL COMMENT '视图标识',
  `ATTRIBUTE` varchar(255) DEFAULT NULL COMMENT '属性名称',
  `ALIAS` varchar(255) DEFAULT NULL COMMENT '显示别名',
  `TYPE` enum('text','textbox','select','date','time') DEFAULT NULL COMMENT '显示方式',
  `LENGTH` int(11) DEFAULT NULL COMMENT '长度',
  `QUERY_TAG` enum('YES','NO') DEFAULT NULL COMMENT '是否做为查询条件',
  `LIST_TAG` enum('YES','NO') DEFAULT NULL COMMENT '是否列表展示',
  `ADD_TAG` enum('YES','NO') DEFAULT NULL COMMENT '是否支持增加',
  `DETAIL_TAG` enum('YES','NO') DEFAULT NULL COMMENT '是否详情页面展示',
  `UPDATE_TAG` enum('NO','UPDATE','VIEW') DEFAULT NULL COMMENT '是否修改页面展示',
  PRIMARY KEY (`PAGE_ATTRIBUTE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8;



